sequenceDiagram
    autonumber
    participant MessageStore_Alice@{ "type" : "database" } as Message store (Alice)
    participant NodeState_Alice@{ "type" : "database" } as Node state (Alice)
    participant PayloadState_Alice@{ "type" : "database" } as Payload state (Alice)
    actor Alice
    actor Bob
    participant PayloadState_Bob@{ "type" : "database" } as Payload state (Bob)
    participant NodeState_Bob@{ "type" : "database" } as Node state (Bob)
    participant MessageStore_Bob@{ "type" : "database" } as Message store (Bob)
    Note over Alice, Bob: batch data sync

    
    Alice->>PayloadState_Alice: create payload with messages
    activate PayloadState_Alice
    PayloadState_Alice->>NodeState_Alice: retrieve message IDs for Bob
    NodeState_Alice->>MessageStore_Alice: retrieve messages with IDs for Bob
    MessageStore_Alice-->>PayloadState_Alice: return messages for Bob
    PayloadState_Alice-->>Alice: return payload with messages for Bob
    Alice->>Bob: send payload with messages
    
    Bob->>PayloadState_Bob: create payload with received payload
    PayloadState_Bob-->>Bob: return payload with received messages
    activate PayloadState_Bob
    par message storing
        Bob->>MessageStore_Bob: store missing messages from payload
        %% maybe separate
        Bob->>NodeState_Bob: wrap: remove messages from NodeState for Alice that they already have send in their payload
    and determination acknowledgements
        Bob->>PayloadState_Bob: add ACKs for received messages to payload
        PayloadState_Bob-->>Bob: return payload with ACKs
    end
    Bob-->>Alice: send payload with ACKs
    deactivate PayloadState_Bob
    deactivate PayloadState_Alice

    Alice->>NodeState_Alice: remove acknowledged messages from NodeState for Bob
