sequenceDiagram
    participant MessageStore_Alice@{ "type" : "database" } as Message store (Alice)
    participant NodeState_Alice@{ "type" : "database" } as Node state (Alice)
    participant PayloadState_Alice@{ "type" : "database" } as Payload state (Alice)
    actor Alice
    actor Bob
    participant PayloadState_Bob@{ "type" : "database" } as Payload state (Bob)
    participant NodeState_Bob@{ "type" : "database" } as Node state (Bob)
    participant MessageStore_Bob@{ "type" : "database" } as Message store (Bob)
    autonumber

    Note over Alice, Bob: batch data sync

    Note over Alice, Bob: wrap: Initial state<br/>MessageStore_Alice = [M1, M2, M3]<br/>MessageStore_Bob = [M1]<br/>NodeState_A->B = <br/>{messages:[M1,M2,M3], offers:[],<br/> requests:[]}<br/>NodeState_B->A = <br/>{messages:[M1], offers:[], requests:[]}

    Alice->>PayloadState_Alice: create payload with messages {messages:[M1,M2,M3], acks:[]}
    activate PayloadState_Alice
    PayloadState_Alice->>NodeState_Alice: retrieve message IDs for Bob
    NodeState_Alice->>MessageStore_Alice: retrieve messages with IDs for Bob to Alice
    MessageStore_Alice-->>PayloadState_Alice: return messages for Bob
    PayloadState_Alice-->>Alice: return payload with messages for Bob
    Alice->>Bob: send payload with messages
    
    Bob->>PayloadState_Bob: create payload with received payload
    PayloadState_Bob-->>Bob: return payload with received messages
    activate PayloadState_Bob
    par message storing
        Bob->>MessageStore_Bob: store missing messages M2 and M3 from payload
        Note right of Bob: Bob already has M1,<br/>so only new messages are added to <br/>MessageStore_Bob.
        
        Bob->>NodeState_Bob: wrap: remove messages from Bob's NodeState to Alice that Alice already <br/>have send in their payload {messages:[], offers:[], requests:[]}
    and determination acknowledgements
        Bob->>PayloadState_Bob: add ACKs for received messages to payload
        PayloadState_Bob-->>Bob: return payload with ACKs
    end
    Bob-->>Alice: send payload with ACKs
    deactivate PayloadState_Bob
    deactivate PayloadState_Alice

    Alice->>NodeState_Alice: remove acknowledged messages from NodeState for Alice to Bob
    Note left of Alice: ACKs for M1, M2, M3 received.<br/>NodeState_A->B becomes {messages:[], offers:[],<br/> requests:[]}.
    Note over Alice, Bob: wrap: Final state<br/>MessageStore_Alice = [M1, M2, M3]<br/>MessageStore_Bob = [M1, M2, M3]<br/>NodeState_A->B =<br/> {messages:[], offers:[], requests:[]}<br/>NodeState_B->A =<br/> {messages:[], offers:[], requests:[]}
